Router.map ->
  @route 'razorpay',
    controller: ShopAdminController
    path: 'dashboard/settings/razorpay',
    template: 'razorpay'
    waitOn: ->
      return ReactionCore.Subscriptions.Packages
  @route 'razorpayPayment',
    path: 'razorpay',
    where: 'server',
    action: ->
      console.log @.request.body
      @.response.end "success"
